BUNDLE_NAME = DingPrefs

DingPrefs_EXTRA_FRAMEWORKS = Cephei CepheiPrefs
DingPrefs_FILES = DIRootListController.m
DingPrefs_FRAMEWORKS = UIKit
DingPrefs_PRIVATE_FRAMEWORKS = Preferences
DingPrefs_INSTALL_PATH = /Library/PreferenceBundles
DingPrefs_CFLAGS = -fobjc-arc -Wdeprecated-declarations -Wno-deprecated-declarations

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
